---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pd
  labels:
    type: appserver
    author: venkat
spec: 
  containers:
    - name: httpd-pod
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 9090
...
